
# Site
title: ❤ MengLi #博客标题
subtitle: 记录成长与爱 ❤ #博客副标题
description: 一个热爱技术却很菜的大龄程序员，记录今后的每一点点进步和生活。 #博客的描述
keywords: mengli,java,blob,
author: MengLi #你的名字
language: zh-CN #网站使用的语言，使用 ISO-639-1，默认 en （这个选项貌似跟主题是否国际化了有关）
timezone: Asia/Shanghai #网站时区 像 America/New_York, Japan, UTC 这种
email: 1061982601@qq.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://imengli.com
root: /
#permalink: :year/:month/:day/:title/article/:abbrlink.html
# 使用这个方法需要安装一个插件：npm install hexo-abbrlink --save
permalink: article/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source #资源文件夹
public_dir: public #公共文件夹
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
code_dir: downloads/code #Include code 文件夹
i18n_dir: :lang #国际化（i18n）文件夹
skip_render: #跳过指定文件的渲染，您可使用 glob 来配置路径。

# Writing
new_post_name: :year-:month-:day-:title.md # 新文章的文件名称
default_layout: post #预设布局
titlecase: false # 把标题转换为单词首字母大写
external_link:
  enable: true # 在新标签中打开链接
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: false #启动 Asset 文件夹，为 true 时，每次建立文件时，Hexo 会自动建立一个与文章同名的文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true #显示未来的文章
highlight: #代码块的设置
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized #默认分类
category_map: #分类别名
tag_map: #标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD HH:mm:ss
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# --------------------------------------------------

# 下面俩都是Md的渲染插件,第一个选软速度快,但是会将渲染不出{},问题未知,等着后面测试一下
# 第二个是的速度慢点,但是现在还没有发现什么问题.

#npm un hexo-renderer-marked --save
#npm i hexo-renderer-markdown-it --save
#npm install markdown-it-emoji --save
# markdown 渲染引擎配置，默认是hexo-renderer-marked，这个插件渲染速度更快，且有新特性
#markdown:
#  render:
#    html: true
#    xhtmlOut: false
#    breaks: true
#    linkify: true
#    typographer: true
#    quotes: '“”‘’'
#  plugins:
#    - markdown-it-footnote
#    - markdown-it-sup
#    - markdown-it-sub
#    - markdown-it-abbr
#    - markdown-it-emoji
#  anchors:
#    level: 2
#    collisionSuffix: 'v'
#    permalink: true
#    permalinkClass: header-anchor
#    permalinkSymbol: ¶


# npm un hexo-renderer-markdown-it --save
# npm un hexo-renderer-marked --save
# npm i hexo-lute --save
lute:
  emoji: true # Disabled by default

# --------------------------------------------------


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly #当前主题名称

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy: #部署
  type: git
  repo: https://github.com/Weijia-Jiang/Weijia-Jiang.github.io #库（Repository）地址
  branch: master #分支名称
